namespace ConsentSyncCore.Services.Eligibility;

/// <summary>Read-only description of an administrative eligibility rule shown in the Criteria Explorer.</summary>
public sealed record EligibilityCriterionDefinition(
    string AppointmentMilestone,
    string MinAge,
    string MaxAge,
    string RequiredInterval,
    string MissingPhisHistoryAction,
    string ClinicalLogicManagementSummary,
    string CalculationExplanation,
    string FrenchCalculationExplanation);

/// <summary>Shared, immutable descriptions and constants for the current NB eligibility rules.</summary>
public static class EligibilityCriteriaCatalog
{
    public const int MmrMmrvMinimumIntervalDays = 180;
    public const int FourMonthMinimumIntervalDays = 28;
    public const int SixMonthMinimumIntervalDays = 56;

    public static IReadOnlyList<EligibilityCriterionDefinition> All { get; } = Array.AsReadOnly<EligibilityCriterionDefinition>(
    [
        new("18 Month Appointment", "18.0 m (inclusive)", "None", "> 180 days after latest MMR or MMRV", "Eligible when no MMR/MMRV dose is found", "Routine 18-month immunization. The client may attend at any age once 18 calendar months is reached.", "The clinic date must be on or after DOB + 18 calendar months. The evaluator finds the latest record whose agent contains MMR or MMRV. If none is found, the client is eligible; otherwise the interval must be strictly greater than 180 days. Exactly 180 days is ineligible.", "La date de la clinique doit être égale ou postérieure à la date de naissance + 18 mois civils. L’évaluateur repère le dossier le plus récent dont l’agent contient MMR ou MMRV. Si aucun dossier n’est trouvé, le client est admissible; sinon, l’intervalle doit être strictement supérieur à 180 jours. Un intervalle d’exactement 180 jours est inadmissible."),
        new("ETS (Assessment Only)", "18.0 m (inclusive)", "24.0 m (exclusive)", "N/A — assessment only", "Eligible; MMR/MMRV history is ignored", "Healthy Toddler Assessment screening only. It has a strict upper age boundary and does not assess vaccine history.", "The clinic date must be on or after DOB + 18 calendar months and before DOB + 24 calendar months. MMR/MMRV records and the availability of PHIS history do not affect this assessment-only result.", "La date de la clinique doit être égale ou postérieure à la date de naissance + 18 mois civils et antérieure à la date de naissance + 24 mois civils. Les dossiers MMR/MMRV et la disponibilité de l’historique PHIS n’influencent pas ce résultat d’évaluation seulement."),
        new("ETS+ (HTA + Vaccine)", "18.0 m (inclusive)", "24.0 m (exclusive)", "> 180 days after latest MMR or MMRV", "Eligible when no MMR/MMRV dose is found", "Combined Healthy Toddler Assessment and 18-month vaccination, with the same strict HTA age window.", "The clinic date must be on or after DOB + 18 calendar months and before DOB + 24 calendar months. The evaluator finds the latest MMR or MMRV record; no matching dose is eligible, while a matching dose requires an interval strictly greater than 180 days.", "La date de la clinique doit être égale ou postérieure à la date de naissance + 18 mois civils et antérieure à la date de naissance + 24 mois civils. L’évaluateur repère le dossier MMR ou MMRV le plus récent; l’absence de dose correspondante rend le client admissible, tandis qu’une dose correspondante exige un intervalle strictement supérieur à 180 jours."),
        new("2 Month Appointment", "2.0 m (inclusive)", "None", "N/A — age rule only", "Manual Review when PHIS history is unavailable", "Routine infant milestone evaluated from the two-calendar-month age boundary.", "A history object must be available. The clinic date must be on or after DOB + 2 calendar months; no vaccine interval is checked for this appointment.", "Un historique doit être disponible. La date de la clinique doit être égale ou postérieure à la date de naissance + 2 mois civils; aucun intervalle entre vaccins n’est vérifié pour ce rendez-vous."),
        new("4 Month Appointment", "No independent age check", "None", ">= 28 days after latest DTaP, DPT, Pneu, or Rota", "Manual Review when PHIS history is unavailable; eligible if no matching dose exists in available history", "Routine infant milestone evaluated from the most recent matching 2-month-series dose interval.", "A history object must be available. The evaluator selects the latest record whose agent contains DTaP, DPT, Pneu, or Rota. If no matching dose exists, the client is eligible; otherwise the interval from that dose to the clinic date must be at least 28 days.", "Un historique doit être disponible. L’évaluateur sélectionne le dossier le plus récent dont l’agent contient DTaP, DPT, Pneu ou Rota. S’il n’existe aucune dose correspondante, le client est admissible; sinon, l’intervalle entre cette dose et la date de la clinique doit être d’au moins 28 jours."),
        new("6 Month Appointment", "No independent age check", "None", ">= 56 days after latest DTaP, DPT, or Pneu", "Manual Review when PHIS history is unavailable; eligible if no matching dose exists in available history", "Routine infant milestone evaluated from the most recent matching 4-month-series dose interval.", "A history object must be available. The evaluator selects the latest record whose agent contains DTaP, DPT, or Pneu. If no matching dose exists, the client is eligible; otherwise the interval from that dose to the clinic date must be at least 56 days.", "Un historique doit être disponible. L’évaluateur sélectionne le dossier le plus récent dont l’agent contient DTaP, DPT ou Pneu. S’il n’existe aucune dose correspondante, le client est admissible; sinon, l’intervalle entre cette dose et la date de la clinique doit être d’au moins 56 jours."),
        new("12 Month Appointment", "12.0 m (inclusive)", "None", "N/A — age rule only", "Manual Review when PHIS history is unavailable", "Routine 12-month milestone evaluated at the first birthday.", "A history object must be available. The clinic date must be on or after the first calendar birthday; no vaccine interval is checked.", "Un historique doit être disponible. La date de la clinique doit être égale ou postérieure au premier anniversaire civil; aucun intervalle entre vaccins n’est vérifié."),
        new("Preschool Appointment", "48.0 m (inclusive)", "None", "N/A — age rule only", "Manual Review when PHIS history is unavailable", "Preschool booster milestone evaluated at the fourth birthday.", "A history object must be available. The clinic date must be on or after the fourth calendar birthday; no vaccine interval is checked.", "Un historique doit être disponible. La date de la clinique doit être égale ou postérieure au quatrième anniversaire civil; aucun intervalle entre vaccins n’est vérifié."),
        new("Other / Autre", "N/A", "None", "Any prior PHIS vaccination record", "Manual Review when history is unavailable; Ineligible when available history has zero doses", "Non-standard or catch-up appointment requiring confirmation of prior PHIS vaccination history.", "A history object must be available. At least one immunization record makes the client eligible. An available history with zero records is ineligible; no history object requires manual review.", "Un historique doit être disponible. Au moins un dossier d’immunisation rend le client admissible. Un historique disponible sans aucun dossier rend le client inadmissible; l’absence d’historique exige une révision manuelle."),
        new("ETS Unknown", "N/A", "N/A", "N/A", "Manual Review", "Ambiguous or unclassified ETS schedule entry requiring administrative review.", "This appointment category is never auto-evaluated. The evaluator returns Manual Review before applying age, interval, or PHIS-history checks.", "Cette catégorie de rendez-vous n’est jamais évaluée automatiquement. L’évaluateur retourne Révision manuelle avant d’appliquer les vérifications d’âge, d’intervalle ou d’historique PHIS.")
    ]);
}
